package treesitter

// builtinsByLang holds the set of builtin/prelude identifiers per language.
// These are names that come from the language runtime or standard prelude,
// and should be annotated as IsBuiltin=true on references (not treated as
// unresolved external symbols).
var builtinsByLang = map[string]map[string]bool{
	"go": goBuiltins,
	"java": javaBuiltins,
	"python": pythonBuiltins,
	"typescript": jstsBuiltins,
	"javascript": jstsBuiltins,
	"rust": rustBuiltins,
}

// IsBuiltin returns true if name is a known builtin for the given language.
func IsBuiltin(lang, name string) bool {
	if m, ok := builtinsByLang[lang]; ok {
		return m[name]
	}
	return false
}

// ---------- Go builtins ----------

var goBuiltins = map[string]bool{
	// builtin functions
	"append":  true,
	"cap":     true,
	"clear":   true,
	"close":   true,
	"complex": true,
	"copy":    true,
	"delete":  true,
	"imag":    true,
	"len":     true,
	"make":    true,
	"max":     true,
	"min":     true,
	"new":     true,
	"panic":   true,
	"print":   true,
	"println": true,
	"real":    true,
	"recover": true,
	// builtin types
	"bool":       true,
	"byte":       true,
	"comparable": true,
	"complex64":  true,
	"complex128": true,
	"error":      true,
	"float32":    true,
	"float64":    true,
	"int":        true,
	"int8":       true,
	"int16":      true,
	"int32":      true,
	"int64":      true,
	"rune":       true,
	"string":     true,
	"uint":       true,
	"uint8":      true,
	"uint16":     true,
	"uint32":     true,
	"uint64":     true,
	"uintptr":    true,
	"any":        true,
	// builtin constants
	"true":  true,
	"false": true,
	"nil":   true,
	"iota":  true,
}

// ---------- Java builtins (java.lang) ----------

var javaBuiltins = map[string]bool{
	// Wrapper types
	"Boolean":   true,
	"Byte":      true,
	"Character": true,
	"Double":    true,
	"Float":     true,
	"Integer":   true,
	"Long":      true,
	"Short":     true,
	"Void":      true,
	"Number":    true,
	// Core classes
	"Object":        true,
	"String":        true,
	"StringBuilder": true,
	"StringBuffer":  true,
	"System":        true,
	"Class":         true,
	"ClassLoader":   true,
	"Thread":        true,
	"Runnable":      true,
	"Math":          true,
	"StrictMath":    true,
	"Runtime":       true,
	"Process":       true,
	"ProcessBuilder": true,
	// Exceptions / errors
	"Throwable":                true,
	"Exception":                true,
	"RuntimeException":         true,
	"Error":                    true,
	"NullPointerException":     true,
	"IllegalArgumentException": true,
	"IllegalStateException":    true,
	"IndexOutOfBoundsException": true,
	"ClassCastException":       true,
	"UnsupportedOperationException": true,
	"ArithmeticException":      true,
	"StackOverflowError":       true,
	"OutOfMemoryError":         true,
	// Interfaces
	"Comparable":  true,
	"Iterable":    true,
	"AutoCloseable": true,
	"Cloneable":   true,
	// Annotations
	"Override":           true,
	"Deprecated":         true,
	"SuppressWarnings":   true,
	"FunctionalInterface": true,
	// Enum
	"Enum": true,
}

// ---------- Python builtins ----------

var pythonBuiltins = map[string]bool{
	// builtin functions
	"abs":            true,
	"all":            true,
	"any":            true,
	"ascii":          true,
	"bin":            true,
	"bool":           true,
	"breakpoint":     true,
	"bytearray":      true,
	"bytes":          true,
	"callable":       true,
	"chr":            true,
	"classmethod":    true,
	"compile":        true,
	"complex":        true,
	"delattr":        true,
	"dict":           true,
	"dir":            true,
	"divmod":         true,
	"enumerate":      true,
	"eval":           true,
	"exec":           true,
	"filter":         true,
	"float":          true,
	"format":         true,
	"frozenset":      true,
	"getattr":        true,
	"globals":        true,
	"hasattr":        true,
	"hash":           true,
	"help":           true,
	"hex":            true,
	"id":             true,
	"input":          true,
	"int":            true,
	"isinstance":     true,
	"issubclass":     true,
	"iter":           true,
	"len":            true,
	"list":           true,
	"locals":         true,
	"map":            true,
	"max":            true,
	"memoryview":     true,
	"min":            true,
	"next":           true,
	"object":         true,
	"oct":            true,
	"open":           true,
	"ord":            true,
	"pow":            true,
	"print":          true,
	"property":       true,
	"range":          true,
	"repr":           true,
	"reversed":       true,
	"round":          true,
	"set":            true,
	"setattr":        true,
	"slice":          true,
	"sorted":         true,
	"staticmethod":   true,
	"str":            true,
	"sum":            true,
	"super":          true,
	"tuple":          true,
	"type":           true,
	"vars":           true,
	"zip":            true,
	// builtin exceptions
	"BaseException":        true,
	"Exception":            true,
	"ArithmeticError":      true,
	"AssertionError":       true,
	"AttributeError":       true,
	"BlockingIOError":      true,
	"BrokenPipeError":      true,
	"BufferError":          true,
	"ChildProcessError":    true,
	"ConnectionError":      true,
	"EOFError":             true,
	"FileExistsError":      true,
	"FileNotFoundError":    true,
	"FloatingPointError":   true,
	"ImportError":          true,
	"IndexError":           true,
	"InterruptedError":     true,
	"IsADirectoryError":    true,
	"KeyError":             true,
	"KeyboardInterrupt":    true,
	"LookupError":          true,
	"MemoryError":          true,
	"ModuleNotFoundError":  true,
	"NameError":            true,
	"NotADirectoryError":   true,
	"NotImplementedError":  true,
	"OSError":              true,
	"OverflowError":        true,
	"PermissionError":      true,
	"ProcessLookupError":   true,
	"RecursionError":       true,
	"ReferenceError":       true,
	"RuntimeError":         true,
	"StopAsyncIteration":   true,
	"StopIteration":        true,
	"SyntaxError":          true,
	"SystemError":          true,
	"SystemExit":           true,
	"TimeoutError":         true,
	"TypeError":            true,
	"UnboundLocalError":    true,
	"UnicodeDecodeError":   true,
	"UnicodeEncodeError":   true,
	"UnicodeError":         true,
	"UnicodeTranslateError": true,
	"ValueError":           true,
	"ZeroDivisionError":    true,
	// builtin constants
	"True":            true,
	"False":           true,
	"None":            true,
	"NotImplemented":  true,
	"Ellipsis":        true,
	"__name__":        true,
	"__doc__":         true,
	"__file__":        true,
}

// ---------- JS / TS builtins (global scope) ----------

var jstsBuiltins = map[string]bool{
	// Global constructors / types
	"Array":          true,
	"ArrayBuffer":    true,
	"BigInt":         true,
	"Boolean":        true,
	"DataView":       true,
	"Date":           true,
	"Error":          true,
	"EvalError":      true,
	"Float32Array":   true,
	"Float64Array":   true,
	"Function":       true,
	"Int8Array":      true,
	"Int16Array":     true,
	"Int32Array":     true,
	"JSON":           true,
	"Map":            true,
	"Math":           true,
	"Number":         true,
	"Object":         true,
	"Promise":        true,
	"Proxy":          true,
	"RangeError":     true,
	"ReferenceError": true,
	"Reflect":        true,
	"RegExp":         true,
	"Set":            true,
	"SharedArrayBuffer": true,
	"String":         true,
	"Symbol":         true,
	"SyntaxError":    true,
	"TypeError":      true,
	"URIError":       true,
	"Uint8Array":     true,
	"Uint8ClampedArray": true,
	"Uint16Array":    true,
	"Uint32Array":    true,
	"WeakMap":        true,
	"WeakRef":        true,
	"WeakSet":        true,
	// Global objects / functions
	"console":        true,
	"setTimeout":     true,
	"clearTimeout":   true,
	"setInterval":    true,
	"clearInterval":  true,
	"setImmediate":   true,
	"clearImmediate": true,
	"queueMicrotask": true,
	"fetch":          true,
	"atob":           true,
	"btoa":           true,
	"parseInt":       true,
	"parseFloat":     true,
	"isNaN":          true,
	"isFinite":       true,
	"encodeURI":      true,
	"decodeURI":      true,
	"encodeURIComponent": true,
	"decodeURIComponent": true,
	"globalThis":     true,
	"undefined":      true,
	"NaN":            true,
	"Infinity":       true,
	// Node.js globals
	"process":  true,
	"Buffer":   true,
	"require":  true,
	"module":   true,
	"exports":  true,
	"__dirname":  true,
	"__filename": true,
	// TS utility types
	"Partial":      true,
	"Required":     true,
	"Readonly":     true,
	"Record":       true,
	"Pick":         true,
	"Omit":         true,
	"Exclude":      true,
	"Extract":      true,
	"NonNullable":  true,
	"Parameters":   true,
	"ReturnType":   true,
	"InstanceType": true,
	"Awaited":      true,
}

// ---------- Rust builtins (prelude + common std) ----------

var rustBuiltins = map[string]bool{
	// Prelude types
	"Option":  true,
	"Some":    true,
	"None":    true,
	"Result":  true,
	"Ok":      true,
	"Err":     true,
	"Box":     true,
	"Vec":     true,
	"String":  true,
	"ToString": true,
	// Prelude traits
	"Clone":        true,
	"Copy":         true,
	"Debug":        true,
	"Default":      true,
	"Display":      true,
	"Drop":         true,
	"Eq":           true,
	"From":         true,
	"Into":         true,
	"Iterator":     true,
	"IntoIterator": true,
	"Ord":          true,
	"PartialEq":    true,
	"PartialOrd":   true,
	"Send":         true,
	"Sized":        true,
	"Sync":         true,
	"Unpin":        true,
	"Hash":         true,
	"AsRef":        true,
	"AsMut":        true,
	"TryFrom":      true,
	"TryInto":      true,
	// Prelude macros (used as functions in tree-sitter)
	"println":  true,
	"print":    true,
	"eprintln": true,
	"eprint":   true,
	"format":   true,
	"vec":      true,
	"todo":     true,
	"unimplemented": true,
	"unreachable":   true,
	"panic":    true,
	"assert":   true,
	"assert_eq": true,
	"assert_ne": true,
	"dbg":      true,
	// Primitive types
	"bool":    true,
	"char":    true,
	"f32":     true,
	"f64":     true,
	"i8":      true,
	"i16":     true,
	"i32":     true,
	"i64":     true,
	"i128":    true,
	"isize":   true,
	"u8":      true,
	"u16":     true,
	"u32":     true,
	"u64":     true,
	"u128":    true,
	"usize":   true,
	"str":     true,
}
